### ISSUE TITLE
`averageScoreAll` crashes the server

### ISSUE THREAD

**Issue by MangoSwirl** [HighlanderRobotics/Scouting-Server#16]
Stack trace
```
Logger -  200 A new GET request from ::1 for /API/analysis/averageScoreAll was received. It took 4.91 milliseconds to be resolved

/Users/collincameron/Documents/FRC/learn-auth-server/analysis/averageScoreAll.js:29
                rows.forEach(functionAdder);
                     ^

TypeError: Cannot read properties of null (reading 'forEach')
    at Statement.<anonymous> (/Users/collincameron/Documents/FRC/learn-auth-server/analysis/averageScoreAll.js:29:22)
    at Statement.replacement (/Users/collincameron/Documents/FRC/learn-auth-server/node_modules/sqlite3/lib/trace.js:25:27)
    at Statement.replacement (/Users/collincameron/Documents/FRC/learn-auth-server/node_modules/sqlite3/lib/trace.js:25:27)
```

**Comment by MangoSwirl** [comment]
@CassieColby will this metric be in Power Play too or should I close it?

**Comment by CassieColby** [comment]
This is going to be in power play possibly. So don't discard it, I still need to fix it, but its impossible to run full test without at least 1 piece of sample data, so I'll do it as soon as I can
